// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gT5XJbKD-3Vfbs3h46dv1rhUU3NEKH8',
    appId: '1:770611096369:web:cc9b8757b7b308e970de10',
    messagingSenderId: '770611096369',
    projectId: 'flutterdenem',
    authDomain: 'flutterdenem.firebaseapp.com',
    storageBucket: 'flutterdenem.appspot.com',
    measurementId: 'G-LRJG0C30B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh7jw1oEbPU9cpPMgn13VtNupLCxKflao',
    appId: '1:770611096369:android:533d93309ddcc52570de10',
    messagingSenderId: '770611096369',
    projectId: 'flutterdenem',
    storageBucket: 'flutterdenem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkEnisakKVv3_AefiyNuIKE9L6ueb4dwU',
    appId: '1:770611096369:ios:2fb24e81907a19d770de10',
    messagingSenderId: '770611096369',
    projectId: 'flutterdenem',
    storageBucket: 'flutterdenem.appspot.com',
    iosClientId:
        '770611096369-b3ni9iu7rftr3hl9chhmqrrb238i51mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkEnisakKVv3_AefiyNuIKE9L6ueb4dwU',
    appId: '1:770611096369:ios:a3d6406047576adb70de10',
    messagingSenderId: '770611096369',
    projectId: 'flutterdenem',
    storageBucket: 'flutterdenem.appspot.com',
    iosClientId:
        '770611096369-eule0tvbrjksd5r1p1ib5rt7fg5100rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase.RunnerTests',
  );
}
